# -*- coding: utf-8 -*-
"""Fake_Logo_Detection_Using_Pattern_Recognition .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbFf3KdqnjM4PkmjIOj11VUTgvEwAQyX

#Import Dataset
"""

from google.colab import files
uploaded = files.upload()

!unzip dataset.zip -d /content/dataset

import os
os.listdir('/content/dataset') #returns a list of all files and folders

!mkdir -p /content/dataset/train/real
!mkdir -p /content/dataset/train/fake

import os
os.listdir('/content/dataset') #returns a list of all files and folders

!mv /content/dataset/output/* /content/dataset/train/real/
!mv /content/dataset/genLogoOutput/* /content/dataset/train/fake/

import os

real_count = len(os.listdir('/content/dataset/train/real'))
fake_count = len(os.listdir('/content/dataset/train/fake'))

print(f"Real logos: {real_count}")
print(f"Fake logos: {fake_count}")

#import library
#build CNN using TensorFlow/Keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

"""#Data Preprocessing step"""

#Loads images from your folders
train_dir = '/content/dataset/train'

"""Create an ImageDataGenerator"""

# Image data generator for training
#Applies transformations (called data augmentation) to improve model learning.
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,   # 80% train, 20% validation
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

# Training data (teaches the model)
train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(128, 128),
    batch_size=32,
    class_mode='binary',
    subset='training'
)

# Validation data (tests the model’s performance after each training epoch)
val_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(128, 128),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

"""#Model Building (CNN Architecture)"""

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(128, 128, 3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')  # Binary classification (real/fake)
])

model.summary()

#perform model compilation to define the optimizer, loss function, and evaluation metric
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

#start learning from the training images, and check your progress after each round.
history = model.fit(
    train_data,
    epochs=10,
    validation_data=val_data
)

#Training Result Visualization
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.show()

#Data Verification
import os

# list a few sample images
real_images = os.listdir('/content/dataset/train/real')[:5]
fake_images = os.listdir('/content/dataset/train/fake')[:5]

print("Real:", real_images)
print("Fake:", fake_images)

#Data Verification (per class)

import os

# Example: list images from real logos of 'Lg'
sample_real_images = os.listdir('/content/dataset/train/real/Lg')[:5]
sample_fake_images = os.listdir('/content/dataset/train/fake/Lg')[:5]

print("Sample real:", sample_real_images)
print("Sample fake:", sample_fake_images)

"""#Testing"""

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
import cv2

# 🔹 Example: test a real logo image
img_path = '/content/dataset/train/real/Lg/000001.jpg'  # Change folder name if needed

# Load and preprocess
test_image = image.load_img(img_path, target_size=(128,128))
img_array = image.img_to_array(test_image)
img_array = np.expand_dims(img_array, axis=0) / 255.0

# Predict
prediction = model.predict(img_array)

# Output result
if prediction[0][0] > 0.5:
    label = "✅ Real Logo"
else:
    label = "❌ Fake Logo"

# Show image and label
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.title(label)
plt.axis('off')
plt.show()

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
import cv2

# 🔹 Example: test a real logo image
img_path = '/content/dataset/train/fake/Amazon/000001.jpg'  # Change folder name if needed

# Load and preprocess
test_image = image.load_img(img_path, target_size=(128,128))
img_array = image.img_to_array(test_image)
img_array = np.expand_dims(img_array, axis=0) / 255.0

# Predict
prediction = model.predict(img_array)

# Output result
if prediction[0][0] > 0.5:
    label = "✅ Real Logo"
else:
    label = "❌ Fake Logo"

# Show image and label
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)
plt.title(label)
plt.axis('off')
plt.show()

"""Confusion Matrix"""

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Get ground truth and predictions from validation generator
val_data.reset()
predictions = model.predict(val_data)
pred_labels = (predictions > 0.5).astype(int).ravel()
true_labels = val_data.classes

# Compute confusion matrix and report
cm = confusion_matrix(true_labels, pred_labels)
cr = classification_report(true_labels, pred_labels, target_names=['Fake', 'Real'])

print("Confusion Matrix:\n", cm)
print("\nClassification Report:\n", cr)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted Fake', 'Predicted Real'],
            yticklabels=['Actual Fake', 'Actual Real'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Fake Logo Detection - Confusion Matrix")
plt.show()

